import { Product } from './product';
export const PRODUCTS: Product[] = [
    {categoryId: 1 , id: 1 , name: 'محصول1' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' ,
     image: 'assets/img/socks.png' , price: 10000},
    {categoryId: 1 , id: 2 , name: 'محصول2' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' ,
     image: 'assets/img/socks.png' , price: 10000},
    {categoryId: 1 , id: 3 , name: 'محصول3' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' ,
     image: 'assets/img/socks.png' , price: 10000},
    {categoryId: 1 , id: 4 , name: 'محصول4' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' ,
    image: 'assets/img/socks.png' , price: 10000},
    {categoryId: 1 , id: 5 , name: 'محصول5' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' ,
     image: 'assets/img/socks.png' , price: 10000},
    {categoryId: 4 , id: 6 , name: 'محصول6' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' ,
     image: 'assets/img/bed.png' , price: 10000},
    {categoryId: 4 , id: 7 , name: 'محصول7' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' ,
     image: 'assets/img/bed.png' , price: 10000},
    {categoryId: 4 , id: 8 , name: 'محصول8' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' ,
     image: 'assets/img/bed.png' , price: 10000},
    {categoryId: 4 , id: 9 , name: 'محصول9' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' ,
     image: 'assets/img/bed.png' , price: 10000},
    {categoryId: 4 , id: 10 , name: 'محصول10' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است',
     image: 'assets/img/bed.png' , price: 10000},
    {categoryId: 2 , id: 11 , name: 'محصول5' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' ,
     image: 'assets/img/bag.png' , price: 10000},
    {categoryId: 2 , id: 12 , name: 'محصول6' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' ,
     image: 'assets/img/bag.png' , price: 10000},
    {categoryId: 2 , id: 13 , name: 'محصول7' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' ,
     image: 'assets/img/bag.png' , price: 10000},
    {categoryId: 2 , id: 14 , name: 'محصول8' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' ,
     image: 'assets/img/bag.png' , price: 10000},
    {categoryId: 2 , id: 15 , name: 'محصول9' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' ,
     image: 'assets/img/bag.png' , price: 10000},
    {categoryId: 2 , id: 16 , name: 'محصول10' , description: '.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است',
     image: 'assets/img/bag.png' , price: 10000}
];
